[project]
name = "crewai-introduction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai[tools]>=0.186.1",
    "langchain-groq>=0.3.8",
    "notebook>=7.4.5",
]
